# Generated by Django 5.0.6 on 2024-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_contact', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=500)),
            ],
        ),
    ]
